/var/log/nginx/winwidget.identity-avatar-backend.access.log {
	daily
	rotate 14
	maxsize 64M
	missingok
	notifempty
	compress
	delaycompress
	create 0640 www-data adm
	sharedscripts
	postrotate
		if [ -s /run/nginx.pid ]; then
			kill -USR1 "$(cat /run/nginx.pid)"
		fi
	endscript
}
