import type { Prisma } from '@prisma/operations-client';

export const ADMIN_EVENT_LOG_SECTIONS = [
	'PAYMENTS',
	'CAMPAIGNS',
	'TASKS',
	'SUBSCRIPTIONS',
	'USERS',
	'BACKLOG',
	'SITE_SETTINGS',
	'TELEGRAM_BOT',
	'AFFILIATE',
	'MESSAGING',
	'REPORTING',
	'DEV_TOOLS',
	'WIDGETS',
	'PLATFORM_CONTENT',
	'SUPPORT'
] as const;

export type AdminEventLogSection =
	(typeof ADMIN_EVENT_LOG_SECTIONS)[number];

export const ADMIN_EVENT_LOG_ACTIONS = [
	'PAYMENT_MANUAL_CHECK',
	'PAYMENT_UNKNOWN_PROVIDER_RESOLVED',
	'PAYMENT_CLEANUP_RUN',
	'AUTO_RENEWAL_ADMIN_PAUSE',
	'AUTO_RENEWAL_ADMIN_RESUME',
	'AUTO_RENEWAL_REVOKE',
	'AUTO_RENEWAL_RECONCILE',
	'AUTO_RENEWAL_TECHNICAL_RESUME',
	'TARIFF_PRICES_UPDATE',
	'LEGAL_PAGE_UPDATE',
	'CAMPAIGN_CREATE',
	'CAMPAIGN_CANCEL',
	'CAMPAIGN_DELIVERY_RETRY',
	'SUBSCRIPTION_ACTIVATE',
	'SUBSCRIPTION_EXTEND_DAYS',
	'SUBSCRIPTION_CANCEL',
	'SUBSCRIPTION_EXPIRY_CHECK_RUN',
	'VERIFICATION_CHALLENGE_CLEANUP_RUN',
	'USER_UPDATE',
	'USER_TOGGLE_ACTIVATION',
	'USER_DELETE',
	'USER_SOFT_DELETE',
	'USER_RESTORE',
	'BACKLOG_TASK_CREATE',
	'BACKLOG_TASK_UPDATE',
	'BACKLOG_TASK_DELETE',
	'SITE_SETTINGS_UPDATE',
	'AFFILIATE_SETTINGS_UPDATE',
	'TELEGRAM_BOT_SETTINGS_UPDATE',
	'TELEGRAM_SCHEDULE_SETTINGS_REJECTED',
	'TELEGRAM_BOT_WEBHOOK_REINSTALL',
	'TELEGRAM_DATABASE_BACKUP_CREATE',
	'TELEGRAM_DATABASE_RESTORE',
	'MESSAGING_FAILURE_RETRY',
	'MESSAGING_FAILURE_CLOSE_WITHOUT_RETRY',
	'BILLING_DELIVERY_RETRY',
	'REPORTING_DAILY_SUMMARY_SETTINGS_UPDATE',
	'REPORTING_DAILY_SUMMARY_SCHEDULE_UPDATE',
	'REPORTING_DAILY_SUMMARY_SCHEDULE_REJECTED',
	'REPORTING_DELIVERY_RETRY',
	'DEV_DATABASE_RESTORE',
	'DEV_DATABASE_RESTORE_PUBLISHED',
	'WIDGET_UPDATE',
	'WIDGET_PUBLISH',
	'WIDGET_DRAFT_DISCARD',
	'WIDGET_VERSION_RESTORE',
	'WIDGET_CLONE',
	'WIDGET_DELETE',
	'WIDGET_BUTTON_IMAGE_UPDATE',
	'WIDGET_DELIVERY_RETRY',
	'WIDGET_DELIVERY_CLOSE',
	'PLATFORM_SITE_SETTINGS_UPDATE',
	'PLATFORM_LEGAL_PAGE_UPDATE',
	'PLATFORM_HOME_PAGE_CONTENT_UPDATE',
	'PLATFORM_HOME_PAGE_RAW_CODE_UPDATE',
	'SUPPORT_ROUTING_SETTINGS_UPDATE',
	'SUPPORT_WEBHOOK_REINSTALL',
	'SUPPORT_DELIVERY_RETRY',
	'SUPPORT_DELIVERY_CLOSE'
] as const;

export type AdminEventLogAction = (typeof ADMIN_EVENT_LOG_ACTIONS)[number];

export interface AdminEventLogRecordInput {
	id?: string;
	adminId?: string | null;
	adminName?: string | null;
	adminEmail?: string | null;
	section: AdminEventLogSection;
	action: AdminEventLogAction;
	description: string;
	entityType?: string | null;
	entityId?: string | null;
	entityLabel?: string | null;
	targetUserId?: string | null;
	targetUserName?: string | null;
	targetUserEmail?: string | null;
	metadata?: Prisma.InputJsonValue;
	ip?: string | null;
	userAgent?: string | null;
}
